cask_args appdir: "/Applications"
tap "caskroom/cask"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/versions"
brew "git"
brew "httpie"
brew "jq"
brew "the_silver_searcher"
brew "tree"
brew "vim"
brew "watchman"
brew "zsh"
brew "node"
brew "nodenv"
cask "iterm2"
cask "alfred"
cask "caffeine"
# cask "1password"
# existing 1password license does not work for 7.x
cask "1password6"
cask "the-unarchiver"
cask "evernote"
cask "shiftit"
cask "sublime-text"
cask "visual-studio-code"
cask "firefox"
cask "google-chrome"
cask "spotify"
cask "flux"
cask "slack"
